ChEn-1070: Introduction to Chemical Engineering Spring 2019 UMass Lowell; Prof. V. F. de Almeida  **08Apr2019**

# 05. Basic Flow Controls in Python
$  
  \newcommand{\Amtrx}{\boldsymbol{\mathsf{A}}}
  \newcommand{\Bmtrx}{\boldsymbol{\mathsf{B}}}
  \newcommand{\Mmtrx}{\boldsymbol{\mathsf{M}}}
  \newcommand{\Imtrx}{\boldsymbol{\mathsf{I}}}
  \newcommand{\Pmtrx}{\boldsymbol{\mathsf{P}}}
  \newcommand{\Lmtrx}{\boldsymbol{\mathsf{L}}}
  \newcommand{\Umtrx}{\boldsymbol{\mathsf{U}}}
  \newcommand{\xvec}{\boldsymbol{\mathsf{x}}}
  \newcommand{\avec}{\boldsymbol{\mathsf{a}}}
  \newcommand{\bvec}{\boldsymbol{\mathsf{b}}}
  \newcommand{\cvec}{\boldsymbol{\mathsf{c}}}
  \newcommand{\rvec}{\boldsymbol{\mathsf{r}}}
  \newcommand{\norm}[1]{\bigl\lVert{#1}\bigr\rVert}
  \DeclareMathOperator{\rank}{rank}
$

---
## Table of Contents
* [Conditionals](#conditionals)
 + [If](#if)
* [Loops](#loops)
 + [For](#for)
---

## Conditionals<a id="conditionals"></a>
Constructs that allow branching of operations. The most importants are:
 1. `if` statement

### `If` statement<a id='if'></a>
The general format is (*indentation observed*):
```python
if test1:        # if test1 is a test statement
    statements1  # associated block
elif test2:      # optional elifs
    statements2
elif test3:      # more optional elifs etc.
    statements3
else:            # optional final else
    statements4
```

Test statements use logical operarors such as: 
 + `==` tests for truth
 + `!=` tests for non-truth
 + `is` type
 + `is not` type
 + `in` inclusion
 + `or` or concatenation of test statements
 + `and` and concatenation of test statements

In [5]:
'''Logical operators'''

a = [1,2,3]

print( a == a )
print( a != a )
print( type(a) is list )
print( type(a) is list() )
print( 3 in a )
print( a is None )
print( a == a and type(a) is int )
print( a[1] == a or type(a) is list )

True
False
True
False
True
False
False
True

### Example
If-else example:
```python
    if lithium is None:      # test if element has type None  
        try:
            import mendeleev  # creates the `name` mendeleev
        except ImportError:
            print('Installing the "mendeleev" package...')
            print('')
            !pip install mendeleev
            import mendeleev
            
        lithium = mendeleev.element('Li')
        print('lithium data: ',[lithium])
        
    else:                 # final test
        print(lithium) # print all info on lithium
```

In [6]:
'''Single if statement'''

lithium = None # initialize with any type

if lithium is None:      # test if element has type None  
    try:
        import mendeleev  # creates the `name` mendeleev
    except ImportError:
        print('Installing the "mendeleev" package...')
        print('')
        !pip install mendeleev
        import mendeleev
        
    lithium = mendeleev.element('Li')
    print('lithium data: ',[lithium])
    
else:
    print('lithium variable: ',lithium) # print everything in lithium

lithium data:  [Element(
	abundance_crust=20.0,
 	abundance_sea=0.18,
 	annotation='',
 	atomic_number=3,
 	atomic_radius=155.0,
 	atomic_radius_rahm=220.00000000000003,
 	atomic_volume=13.1,
 	atomic_weight=6.94,
 	atomic_weight_uncertainty=None,
 	block='s',
 	boiling_point=1118.15,
 	c6=1392.0,
 	c6_gb=1410.0,
 	cas='7439-93-2',
 	covalent_radius_bragg=150.0,
 	covalent_radius_cordero=128.0,
 	covalent_radius_pyykko=133.0,
 	covalent_radius_pyykko_double=124.0,
 	covalent_radius_pyykko_triple=None,
 	covalent_radius_slater=145.0,
 	cpk_color='#b22222',
 	density=0.534,
 	description='Socket silvery metal. First member of group 1 of the periodic table. Lithium salts are used in psychomedicine.',
 	dipole_polarizability=164.0,
 	discoverers='Johann Arfwedson',
 	discovery_location='Sweden',
 	discovery_year=1817,
 	ec=<ElectronicConfiguration(conf="1s2 2s1")>,
 	econf='[He] 2s',
 	electron_affinity=0.618049,
 	en_allen=5.392,
 	en_ghosh=0.105093,
 	en_pauling=0.98,
 	evaporation_heat=148.0,
 	fusion_heat=2.89,
 	gas_basicity=None,
 	geochemical_class='alkali metal',
 	goldschmidt_class='litophile',
 	group=<Group(symbol=IA, name=Alkali metals)>,
 	group_id=1,
 	heat_of_formation=159.3,
 	ionic_radii=[IonicRadius(
	atomic_number=3,
 	charge=1,
 	coordination='IV',
 	crystal_radius=73.0,
 	econf='1s2',
 	id=212,
 	ionic_radius=59.0,
 	most_reliable=True,
 	origin='',
 	spin='',
), IonicRadius(
	atomic_number=3,
 	charge=1,
 	coordination='VI',
 	crystal_radius=90.0,
 	econf='1s2',
 	id=213,
 	ionic_radius=76.0,
 	most_reliable=True,
 	origin='',
 	spin='',
), IonicRadius(
	atomic_number=3,
 	charge=1,
 	coordination='VIII',
 	crystal_radius=106.0,
 	econf='1s2',
 	id=214,
 	ionic_radius=92.0,
 	most_reliable=False,
 	origin='calculated, ',
 	spin='',
)],
 	is_monoisotopic=None,
 	is_radioactive=False,
 	isotopes=[<Isotope(Z=3, A=6, mass=6.015122887)>, <Isotope(Z=3, A=7, mass=7.01600344)>],
 	jmol_color='#cc80ff',
 	lattice_constant=3.49,
 	lattice_structure='BCC',
 	melting_point=553.69,
 	mendeleev_number=1,
 	metallic_radius=123.0,
 	metallic_radius_c12=155.0,
 	molcas_gv_color='#cc80ff',
 	name='Lithium',
 	name_origin='Greek: lithos (stone).',
 	period=2,
 	proton_affinity=None,
 	screening_constants=[<ScreeningConstant(Z=   3, n=  1, s=s, screening=    0.3094)>, <ScreeningConstant(Z=   3, n=  2, s=s, screening=    1.7208)>],
 	sources='Obtained by passing electric charge through melted lithium chloride and from the silicate mineral called spodumene [LiAl(Si2O6)].',
 	specific_heat=3.489,
 	symbol='Li',
 	thermal_conductivity=84.8,
 	uses='Used in batteries. Also for certain kinds of glass and ceramics.  Some is used in lubricants.',
 	vdw_radius=182.0,
 	vdw_radius_alvarez=212.0,
 	vdw_radius_batsanov=220.00000000000003,
 	vdw_radius_bondi=181.0,
 	vdw_radius_dreiding=None,
 	vdw_radius_mm3=254.99999999999997,
 	vdw_radius_rt=None,
 	vdw_radius_truhlar=None,
 	vdw_radius_uff=245.1,
)]

In [7]:
'''Testing example'''

test = 8 # change this to 1, 2 or 3

# test setup (uses multiway branching)
if test == 1:
    print('made to 1')
elif test == 2:
    print('made to 2')
elif test == 3:
    print('made to 3')
else:
    print('Error: test must be 1, 2, or 3.')

Error: test must be 1, 2, or 3.

## Loops<a id="loops"></a>
Contructs that allow repetitive actions on data. There are two basic types: 
 1. `for` loops

### `For` loops<a id='for'></a>
The general format is (*indentation observed*):
```python
for target in container: # assign container items to target
    statements            # repeated loop body: (possibly) use target
    if test: 
        break             # exit loop now; skip else
    if test: 
        continue          # go to top of the loop now
    else:                 # optional else part
        statements        # if did not hit a `break`
#end for target in object:
```

### Example
```python
for i in range(10): # assign i to objects in range(mtrx.shape[0])
    j = 2*i         # loop over this statement with varying i
    print(j)        # print j
#end for i in range(10):
```

In [8]:
'''Simple for loop'''

for i in range(10): # assign i to objects in range(10)
    j = 2*i         # loop over this statement with varying i
    print(j)        # print j

0
2
4
6
8
10
12
14
16
18

In [9]:
'''Simple for loop'''

for i in range(0,18,2): # assign i to objects in range(10,2)
    print(i)            # print i

0
2
4
6
8
10
12
14
16

In [10]:
'''Using a dictionary to create a table'''

import pandas as pd

hydrogen  = {'symbol':'H',  'atomic number':1, 'group':1,  'period':1, 'isotopes':[1,2,3]}
helium    = {'symbol':'He', 'atomic number':2, 'group':18, 'period':1, 'isotopes':[3,4]}
lithium   = {'symbol':'Li', 'atomic number':3, 'group':1,  'period':2, 'isotopes':[6,7]}
beryllium = {'symbol':'Be', 'atomic number':4, 'group':2,  'period':2, 'isotopes':[9,10]}
boron     = {'symbol':'B',  'atomic number':5, 'group':13, 'period':2, 'isotopes':[10,11]}

data = {'hydrogen':hydrogen,'helium':helium,'lithium':lithium,'beryllium':beryllium,'boron':boron}

df1 = pd.DataFrame(data) # pass the dictonary to the data frame

In [11]:
df1

                hydrogen  helium lithium beryllium     boron
atomic number          1       2       3         4         5
group                  1      18       1         2        13
isotopes       [1, 2, 3]  [3, 4]  [6, 7]   [9, 10]  [10, 11]
period                 1       1       2         2         2
symbol                 H      He      Li        Be         B

In [13]:
#lithium.series

In [16]:
'''Create a similar table using mendeleev data'''

# the intention here is to use this list as rows labels
index = ['atomic number', 'group', 'isotopes', 'period', 'symbol' ]

# columwise data in the form of a dictionary
data = dict() # initialize empty dict to hold data

num_elements = 5 # set total number of chemical elements and atomic number

for i in range(1,num_elements+1):  # loop over indices 0 to ...
    ele = mendeleev.element(i) # get chemical element with atomic number i+1
    
    column_data = list()  # initialize empty list to hold the column data
    
    column_data.append(ele.atomic_number)  # get and store atomic number
    column_data.append(ele.group_id)       # get and store group id
    
    mass_number_list = list()
    for iso in ele.isotopes:
        a = iso.mass_number
        mass_number_list.append(a)
        
    #column_data.append( mass_number_list )   
    
    column_data.append([iso.mass_number for iso in ele.isotopes]) # get and store isotope mass numbers
    
    column_data.append(ele.period)         # get and store element period
    column_data.append(ele.symbol)         # get and store element symbol
    
    # store column data in the dictionary key: column label
    data[ele.name] = pd.Series(column_data, index) # value: pd.Series
    
#end for i in range(5):

df2 = pd.DataFrame(data) # pass the dictionary to the data frame

In [17]:
df2

                Hydrogen  Helium Lithium Beryllium     Boron
atomic number          1       2       3         4         5
group                  1      18       1         2        13
isotopes       [1, 2, 3]  [3, 4]  [6, 7]       [9]  [10, 11]
period                 1       1       2         2         2
symbol                 H      He      Li        Be         B